language: python
python:
    - "2.7"
env: 
    - CKANVERSION=master PGVERSION=9.1
    - CKANVERSION=2.2 PGVERSION=9.1
    - CKANVERSION=2.3 PGVERSION=9.1
install:
    - ./bin/travis-build.bash
    - pip install coveralls
script: ./bin/travis-run.sh
after_success:
    - coveralls
